### PR TITLE
Add a how-to guide for using ent and atlas

### PR DESCRIPTION
**Pull request by Minivera**
This is based on the discussion here: https://github.com/encoredev/encore/discussions/307, and my own usage of ent within my application. This is fairly early and there might be a better way of doing this with features of Encore I don't know yet.

It's very easy to integrate a heavy ORM like ent with Encore if you're okay with tinkering a bit with scripts and commands. This guide shows one way of doing it, which could be expanded, but this seems to work really well on my end. We could also add a section for using only Atlas if it could be useful.

Any feedback is very much appreciated!

### CODE REVIEW

**Comment by eandre** [comment]
This looks great, thank you @Minivera!

**Comment by Minivera** [comment]
@eandre just letting you know that I made some quick changes to some of the code to make sure it really works, and so the build will need to be manually approved again. It should be good on my end now 🙂

**Comment by eandre** [comment]
Thanks @Minivera! For this to show up in the Encore website docs it needs to be added to the `docs.cue` file, at the end of the `how-to` section. If you can add that then I think this is ready to merge.

**Comment by Minivera** [comment]
Ha! I hadn't realized I needed to do that, my bad. Should be good now.

**Review by eandre — APPROVED** [review]
Thank you!

**Pull request merged**
